In [35]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score

from sklearn

In [36]:
train = pd.read_csv("train_BigMartSales_Preprocessed.csv")
test = pd.read_csv("test_BigMartSales_Preprocessed.csv")

In [37]:
train.head()

Item_Fat_Content_Low Fat  Item_Fat_Content_Regular  Item_Type_Baking Goods  \
0                         1                         0                       0   
1                         0                         1                       0   
2                         1                         0                       0   
3                         0                         1                       0   
4                         1                         0                       0   

   Item_Type_Breads  Item_Type_Breakfast  Item_Type_Canned  Item_Type_Dairy  \
0                 0                    0                 0                1   
1                 0                    0                 0                0   
2                 0                    0                 0                0   
3                 0                    0                 0                0   
4                 0                    0                 0                0   

   Item_Type_Frozen Foods  Item_Type_Fruits and Vegetables  \
0                       0                                0   
1                       0                                0   
2                       0                                0   
3                       0                                1   
4                       0                                0   

   Item_Type_Hard Drinks  ...  Item_Identifier_2_NC  \
0                      0  ...                     0   
1                      0  ...                     0   
2                      0  ...                     0   
3                      0  ...                     0   
4                      0  ...                     1   

   Outlet_Type_Category_Grocery  Outlet_Type_Category_Supermarket  \
0                             0                                 1   
1                             0                                 1   
2                             0                                 1   
3                             1                                 0   
4                             0                                 1   

   Item_Weight  Item_Visibility  Item_MRP  Item_Outlet_Sales  Outlet_Age  \
0         9.30         0.016047  249.8092          3735.1380          21   
1         5.92         0.019278   48.2692           443.4228          11   
2        17.50         0.016760  141.6180          2097.2700          21   
3        19.20         0.022930  182.0950           732.3800          22   
4         8.93         0.014670   53.8614           994.7052          33   

   Item_Identifier  Outlet_Identifier  
0            FDA15             OUT049  
1            DRC01             OUT018  
2            FDN15             OUT049  
3            FDX07             OUT010  
4            NCD19             OUT013  

[5 rows x 40 columns]

In [38]:
train_X = train.drop(columns= ["Item_Outlet_Sales","Item_Identifier", "Outlet_Identifier"])

In [39]:
test_X = test.drop(columns= ["Item_Outlet_Sales","Item_Identifier", "Outlet_Identifier"])

In [40]:
train_y = train["Item_Outlet_Sales"]

In [41]:
model = LinearRegression()

In [42]:
model.fit(train_X, train_y)

LinearRegression()

In [43]:
pred_train = model.predict(train_X)
pred_test = model.predict(test_X)

In [44]:
pred_test = abs(pred_test)

In [45]:
print("RMSE of Train Data = ",np.sqrt(mean_squared_error(train_y, pred_train)))

RMSE of Train Data =  1127.757956620502


In [46]:
score = cross_val_score(model, train_X, train_y, cv = 10, scoring = "neg_root_mean_squared_error" )

In [13]:
score

array([-1165.04446963, -1138.37414973, -1123.31798712, -1121.63174236,
       -1122.41893765, -1110.78315406, -1116.96652607, -1142.97921986,
       -1139.51916616, -1146.68883668])

In [47]:
np.mean(np.abs(score))

1132.7724189322107

In [48]:
sample = pd.read_csv("https://datahack-prod.s3.amazonaws.com/sample_submission/sample_submission_8RXa3c6.csv")

In [49]:
sample.columns

Index(['Item_Identifier', 'Outlet_Identifier', 'Item_Outlet_Sales'], dtype='object')

In [17]:
sample["Item_Outlet_Sales"] = pred_test

In [18]:
sample.columns

Index(['Item_Identifier', 'Outlet_Identifier', 'Item_Outlet_Sales'], dtype='object')

In [19]:
test_result_upload = pd.concat([test[["Item_Identifier", "Outlet_Identifier"]], pd.DataFrame(pred_test)], axis = 1)

In [20]:
test_result_upload.columns = ['Item_Identifier', 'Outlet_Identifier', 'Item_Outlet_Sales']

In [21]:
test_result_upload

Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0              FDW58            OUT049        1829.356987
1              FDW14            OUT017        1556.480606
2              NCN55            OUT010        1882.605254
3              FDQ58            OUT017        2614.677418
4              FDY38            OUT027        5136.462241
...              ...               ...                ...
5676           FDB58            OUT046        2299.373457
5677           FDD47            OUT018        2467.643022
5678           NCO17            OUT045        1883.657933
5679           FDJ26            OUT017        3603.133774
5680           FDU37            OUT045        1349.362340

[5681 rows x 3 columns]

In [22]:
test_result_upload.to_csv("test_result_Linear_regression.csv", index = False)

In [23]:
model.coef_

array([-2.07750568e+01,  2.07750568e+01, -2.77714889e+00,  3.04826529e+00,
        1.47507627e+00,  2.36598396e+01, -5.37547096e+01, -3.03101136e+01,
        2.65798727e+01, -5.11926052e+01,  4.27910488e+00, -2.38302139e+01,
       -1.96179486e+00, -7.44099015e+00,  1.82529602e+02, -1.33059775e+01,
       -7.72669734e+01,  2.02687669e+01,  5.19696234e+02, -2.42532215e+02,
       -2.77164018e+02,  2.08072178e+02,  3.94131336e+01, -2.47485312e+02,
       -6.58014127e+02, -4.51793622e+02, -6.81412965e+02,  1.79122071e+03,
        3.73526642e+01, -1.03605650e+01, -2.69920992e+01, -6.58014127e+02,
        6.58014127e+02, -4.98760204e-01, -1.72828238e+02,  1.55776052e+01,
       -3.10548611e+01])

In [24]:
model.intercept_

685.61212450068

In [54]:
from sklearn.preprocessing import PolynomialFeatures

In [55]:
poly = PolynomialFeatures(degree = 2)

In [58]:
new_X = poly.fit_transform(train_X)
model = LinearRegression()

In [59]:
model.fit(new_X, train_y)

LinearRegression()

In [61]:
model.coef_

array([ 8.06402360e-08,  5.62323909e+01, -5.62323917e+01,  4.46154866e+01,
        5.56869193e+01, -6.09600529e+02,  4.06154492e+02,  1.74963046e+02,
        1.76110771e+02,  1.90973808e+02,  6.15069610e+02, -1.01409720e+02,
        3.62305982e+01,  3.21639395e+02,  1.03017763e+02, -1.79827188e+03,
        3.13654830e+02,  3.50561967e+02, -2.79396561e+02,  4.63116008e+00,
        2.47912931e+00, -7.11028937e+00,  1.18574204e+00, -5.70732005e+00,
        4.52157801e+00,  1.08938745e+00, -5.26093082e+00,  3.25173233e+00,
        9.19811058e-01, -1.92679637e+02,  1.54840996e+02,  3.78386415e+01,
        1.08938744e+00, -1.08938744e+00,  2.00076057e+02, -4.02321780e+03,
        6.69528552e+00,  2.42925199e+02,  5.62323917e+01,  3.19822391e-10,
       -7.77697609e+01,  8.50396996e+01, -3.53382384e+02,  2.02918406e+02,
        2.78647194e+01,  7.63879021e+01,  7.88119897e+01,  6.15069610e+02,
       -1.01409720e+02,  3.62305982e+01,  1.53341354e+02,  1.03017763e+02,
       -1.05190575e+03,  

In [62]:
pred_df = model.predict(new_X)

In [65]:
import matplotlib.pyplot as plt
plt.scatter

<function matplotlib.pyplot.scatter(x, y, s=None, c=None, marker=None, cmap=None, norm=None, vmin=None, vmax=None, alpha=None, linewidths=None, verts=<deprecated parameter>, edgecolors=None, *, plotnonfinite=False, data=None, **kwargs)>

In [66]:
pred_train = model.predict(new_X)

In [69]:
print("RMSE of train data",np.sqrt(mean_squared_error(train_y, pred_train)))

RMSE of train data 1055.7261560924858


In [ ]:
model = DecisionTreeRegressor